# Configurations
title:            szer0v0_blog
longtitle:        Hello it's me
author:           Kim Soyeong
email:            noname1956@hanyang.ac.kr
description: >
  푸힣힣
cover: /assets/dinosaur.gif

version:          1.0
gitbook_version:  3.2.3
url:              "https://szer0v0.github.io"
baseurl:          ''
rss:              RSS

# bootstrap: use the remote theme for the site itself
# remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min:   1
  h_max:   4

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

# 왼쪽 사이드바 메뉴판
collections:
  pages:
    output: true # 블로그 화면에 보여주겠다 
    permalink: /:collection/:path/ # 주소창에 찍힐 링크
  others:
    output: true
    permalink: /:collection/:path/
  guideline:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - posts
  - guideline
  - pages
  - others

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
